# Generated by Django 5.1.2 on 2024-11-08 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_order_original_cart_order_stripe_pid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='price',
        ),
    ]
