# Generated by Django 5.1.2 on 2024-10-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_photo_description_alter_photo_size_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='size',
            field=models.CharField(default='8x10 inches', max_length=50),
        ),
    ]
