# Generated by Django 5.1.2 on 2024-10-24 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_photo_is_featured_alter_photo_image'),
        ('home', '0006_photo_is_featured'),
    ]

    operations = [
    ]
